name: Get ECR Image Scan Results
description: Determine the next container image tag
inputs:
  registry:
    description: The url for the regsitry
    required: true
  repository-name:
    description: The name of the repository for the container image
    required: true
  tag:
    description: The container image tag
    required: true
runs:
  using: composite
  steps:
    - name: Get ECR Image Scan Results
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1 -Registry '${{ inputs.registry }}' -RepositoryName '${{ inputs.repository-name }}' -Tag '${{ inputs.tag }}'
